public with sharing class MarketingAppContentController {
/* --- SM : Commenting to change Object Name
    @AuraEnabled(cacheable=true)
     public static List<App_Marketing_Content__c>  getContentURLs(String publishedAppId) {
       // return [SELECT External_URL__c,Name FROM App_Marketing_Content__c WHERE Published_App_ID__c =: publishedAppId AND File_Type__c = 'Video'];
       return null;
    }
---*/    
}